chatPrefix: "&8[&eEnchantment Upgrades&8]"
mainMenuTitle: "Enchantment Upgrades"
confirmMenuTitle: "Confirm Enchantment Upgrade"
confirmItem: "green_stained_glass_pane" #Block to be used in the confirm menu to represent accepting
cancelItem: "red_stained_glass_pane" #Block to be used in the confirm menu to represent cancelling
currencyNamePlural: "money" #The plural name of your currency (e.g. money, dollars, coins)
currencySymbolFormat: "&6$x" #The color, symbol, and format of your currency. The "x" represents the amount and will be replaced (e.g. &6$x = $1.00 in gold, &ax€ = 1.00€ in lime)

#Tools that can have their enchantments upgraded
validTools:
  - wooden_hoe
  - stone_hoe
  - golden_hoe
  - iron_hoe
  - diamond_hoe
  - netherite_hoe
  - wooden_pickaxe
  - stone_pickaxe
  - golden_pickaxe
  - iron_pickaxe
  - diamond_pickaxe
  - netherite_pickaxe
  - wooden_axe
  - stone_axe
  - golden_axe
  - iron_axe
  - diamond_axe
  - netherite_axe
  - wooden_sword
  - stone_sword
  - golden_sword
  - iron_sword
  - diamond_sword
  - netherite_sword
  - wooden_shovel
  - stone_shovel
  - golden_shovel
  - iron_shovel
  - diamond_shovel
  - netherite_shovel

#These multipliers are multiplied by the level of the current enchantment to create the cost (multiplier * level = upgrade cost).
#The plugin should be able to detect custom enchants registered by other enchantments if they are correctly registered. For example, enchantments from the Enchantment Solution plugin are detected.
upgradeCostMultipliers:
  efficiency: 1.0
  fortune: 5.0
  unbreaking: 2.0
  width_plus_plus: 500.0 #Example from EnchantmentSolution
  default: 50.0

#Items that represent enchantments in the menu
enchantmentItemRepresentations:
  sharpness: "iron_sword"
  bane_of_arthropods: "spider_eye"
  knockback: "stick"
  smite: "zombie_head"
  fire_aspect: "blaze_powder"
  looting: "iron_ingot"
  sweeping_edge: "stone_axe"
  efficiency: "clock"
  fortune: "diamond"
  silk_touch: "diamond_ore"
  power: "golden_apple"
  flame: "magma_cream"
  punch: "piston"
  infinity: "spectral_arrow"
  luck_of_the_sea: "enchanted_book"
  lure: "fishing_rod"
  loyalty: "prismarine_crystals"
  impaling: "trident"
  riptide: "tube_coral"
  channeling: "campfire"
  quick_charge: "crossbow"
  multishot: "tipped_arrow"
  piercing: "arrow"
  unbreaking: "nether_star"
  mending: "book"
  curse_of_vanishing: "paper"
  angler: "tropical_fish"
  width_plus_plus: "prismarine_slab" #Example for EnchantmentSolution
  default: "red_concrete"

#Set custom max levels for enchantments. If an enchantment max level is unset, the vanilla default value is used.
maximumEnchantmentLevels:
  efficiency: 250
  fortune: 30
  unbreaking: 300