name: EnchantmentUpgrades
version: 0.1.1
main: me.meowso.enchantmentupgrades.EnchantmentUpgrades
api-version: 1.16
authors: [meowsome]
description: Minecraft Spigot plugin to upgrade enchantments on any tool with a menu using Vault
depend: [Vault]
permissions:
  enchantmentupgrades.upgrade:
    description: Allow users to upgrade enchantments
    default: true